version: '3.5'

services:
  postgres-odoo-base-15-04:
    container_name: postgres_odoo-base-15-04
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      PGDATA: /data/postgres
    volumes:
      - /home/ttdn/ttdn_k15/database_ttdn/cntt15_04_db/_data:/data/postgres
    ports:
      - "5434:5432"

volumes:
  odoo-db-data: {}
